/**
 * src/lib/exporters/dossier-exporter.ts
 *
 * Pre-Flight Dossier Exporter for Academic PIs and Co-Authors.
 * Generates client-side formatted Markdown, HTML, and JSON audit dossiers
 * proving citation verification, DOI validity, and retraction checks.
 *
 * Security Hardened: Full HTML entity sanitization on all manuscript inputs
 * to prevent Stored XSS attacks in exported standalone HTML documents.
 */

export interface DossierAuditFinding {
  id: string;
  line: number;
  type: string;
  severity: 'Critical' | 'High' | 'Medium' | 'Low' | string;
  claim?: string;
  context?: string;
  suggestedFix?: string;
  doi?: string;
  entailmentStatus?: 'verified' | 'supported' | 'contradicted' | 'tenuous' | 'unverified';
}

export interface DossierMetadata {
  manuscriptTitle: string;
  authorEmail?: string;
  auditTimestamp: string;
  deskRejectionScore: number;
  totalCitations: number;
  verifiedCount: number;
  retractionCount: number;
  brokenDoiCount: number;
  missingBibCount: number;
  /** Count of missing canonical baselines detected by Gemini Blindspot Radar. */
  missingBaselineCount?: number;
}

export interface DossierExportResult {
  markdown: string;
  html: string;
  json: string;
  downloadAs: (format: 'html' | 'md' | 'json', filename?: string) => void;
  /**
   * Returns a plain-text PI Handoff Email body ready to paste into any email client.
   * Pure string — no DOM dependency, safe in SSR/test contexts.
   */
  copyPIHandoffEmail: () => string;
}

/**
 * Escapes HTML characters to prevent XSS in standalone exported HTML files.
 */
export function escapeHtml(str: string | undefined | null): string {
  if (!str) return '';
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}

export function generatePreFlightDossier(
  meta: DossierMetadata,
  findings: DossierAuditFinding[]
): DossierExportResult {
  const dateFormatted = new Date(meta.auditTimestamp || Date.now()).toUTCString();
  const cleanTitle = escapeHtml(meta.manuscriptTitle);
  const riskStatus =
    meta.deskRejectionScore >= 90 ? 'PASS READY (Low Risk)' :
    meta.deskRejectionScore >= 70 ? 'REVIEW ADVISED (Medium Risk)' :
    'DESK-REJECTION HAZARD (High Risk)';

  const riskColor =
    meta.deskRejectionScore >= 90 ? '#10B981' :
    meta.deskRejectionScore >= 70 ? '#F59E0B' :
    '#EF4444';

  const baselineCount = meta.missingBaselineCount ?? 0;

  // 1. Markdown Generation
  const markdown = `# CiteAssist AI: Pre-Flight Citation Dossier
**Manuscript**: ${meta.manuscriptTitle}  
**Audit Timestamp**: ${dateFormatted}  
**Desk-Rejection Risk Score**: ${meta.deskRejectionScore}/100 — **${riskStatus}**  

---

## Executive Summary
- **Total Citations Scanned**: ${meta.totalCitations}
- **Verified Valid & Grounded**: ${meta.verifiedCount}
- **Retracted Literature Flags**: ${meta.retractionCount}
- **Broken / Dead DOIs**: ${meta.brokenDoiCount}
- **Missing BibTeX Entries**: ${meta.missingBibCount}
- **Missing Canonical Baselines**: ${baselineCount}

---

## Detailed Audit Findings & Remediation

| Line | Severity | Issue Type | In-Text Claim / Context | Recommended Action |
|:---|:---|:---|:---|:---|
${findings.length > 0 ? findings.map(f => `| L${f.line} | **${f.severity}** | ${f.type} | \`${(f.claim || f.context || '').slice(0, 60).replace(/\|/g, '\\|')}\` | ${f.suggestedFix || 'Review citation source'} |`).join('\n') : '| - | Passed | Clean | No citation defects detected. | Manuscript passes pre-flight checks. |'}

---
*Generated by CiteAssist AI — Academic Integrity & Submission Firewall.*
`;

  // 2. HTML Generation (Self-contained, dark academic theme, XSS-hardened)
  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Pre-Flight Dossier: ${cleanTitle}</title>
  <style>
    :root {
      --bg: #090A0C;
      --card-bg: #111418;
      --border: #22272E;
      --text: #E6EDF3;
      --text-muted: #8B949E;
      --accent: #10B981;
      --danger: #F85149;
      --warning: #D29922;
    }
    body {
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
      background-color: var(--bg);
      color: var(--text);
      margin: 0;
      padding: 40px 20px;
      line-height: 1.6;
    }
    .container {
      max-width: 900px;
      margin: 0 auto;
    }
    .header {
      background: var(--card-bg);
      border: 1px solid var(--border);
      border-radius: 12px;
      padding: 24px;
      margin-bottom: 24px;
      box-shadow: 0 4px 20px rgba(0,0,0,0.5);
    }
    .badge {
      display: inline-block;
      padding: 4px 12px;
      border-radius: 999px;
      font-weight: 700;
      font-size: 14px;
      background: ${riskColor}22;
      color: ${riskColor};
      border: 1px solid ${riskColor}66;
    }
    .metrics {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(160px, 1fr));
      gap: 16px;
      margin-top: 20px;
    }
    .metric-card {
      background: #161B22;
      padding: 16px;
      border-radius: 8px;
      border: 1px solid var(--border);
      text-align: center;
    }
    .metric-value {
      font-size: 24px;
      font-weight: 800;
      color: #FFF;
      font-family: monospace;
    }
    .metric-label {
      font-size: 11px;
      color: var(--text-muted);
      text-transform: uppercase;
      letter-spacing: 0.05em;
    }
    table {
      width: 100%;
      border-collapse: collapse;
      background: var(--card-bg);
      border-radius: 8px;
      overflow: hidden;
      border: 1px solid var(--border);
      margin-top: 24px;
    }
    th, td {
      padding: 12px 16px;
      text-align: left;
      border-bottom: 1px solid var(--border);
      font-size: 13px;
    }
    th {
      background: #161B22;
      color: var(--text-muted);
      font-weight: 600;
      font-size: 12px;
      text-transform: uppercase;
    }
    .severity-critical { color: var(--danger); font-weight: bold; }
    .severity-high { color: var(--danger); font-weight: bold; }
    .severity-medium { color: var(--warning); font-weight: bold; }
    .severity-low { color: #58A6FF; font-weight: bold; }
    .footer {
      margin-top: 40px;
      text-align: center;
      font-size: 12px;
      color: var(--text-muted);
    }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <div style="display: flex; justify-content: space-between; align-items: flex-start;">
        <div>
          <h1 style="margin: 0 0 8px 0; font-size: 22px;">CiteAssist AI: Pre-Flight Dossier</h1>
          <p style="margin: 0; color: var(--text-muted); font-size: 13px;"><b>Manuscript:</b> ${cleanTitle}</p>
          <p style="margin: 4px 0 0 0; color: var(--text-muted); font-size: 12px;"><b>Audit Date:</b> ${escapeHtml(dateFormatted)}</p>
        </div>
        <div style="text-align: right;">
          <div class="badge">${meta.deskRejectionScore}/100 ${escapeHtml(riskStatus)}</div>
        </div>
      </div>

      <div class="metrics">
        <div class="metric-card">
          <div class="metric-value">${meta.totalCitations}</div>
          <div class="metric-label">Citations Scanned</div>
        </div>
        <div class="metric-card">
          <div class="metric-value" style="color: ${riskColor};">${meta.verifiedCount}</div>
          <div class="metric-label">Clean &amp; Verified</div>
        </div>
        <div class="metric-card">
          <div class="metric-value" style="color: var(--danger);">${meta.retractionCount}</div>
          <div class="metric-label">Retraction Flags</div>
        </div>
        <div class="metric-card">
          <div class="metric-value" style="color: var(--warning);">${meta.brokenDoiCount}</div>
          <div class="metric-label">Broken DOIs</div>
        </div>
        <div class="metric-card">
          <div class="metric-value" style="color: #6366F1;">${baselineCount}</div>
          <div class="metric-label">Missing Baselines</div>
        </div>
      </div>
    </div>

    <h2 style="font-size: 16px; margin: 24px 0 12px 0;">Remediation & Integrity Checklist</h2>
    <table>
      <thead>
        <tr>
          <th>Line</th>
          <th>Severity</th>
          <th>Issue Type</th>
          <th>Citation Context</th>
          <th>Fix Recommendation</th>
        </tr>
      </thead>
      <tbody>
        ${findings.length > 0 ? findings.map(f => `
        <tr>
          <td style="font-family: monospace;">L${f.line}</td>
          <td class="severity-${escapeHtml((f.severity || '').toLowerCase())}">${escapeHtml(f.severity)}</td>
          <td>${escapeHtml(f.type)}</td>
          <td style="color: var(--text-muted);">${escapeHtml((f.claim || f.context || '').slice(0, 100))}</td>
          <td>${escapeHtml(f.suggestedFix || 'Review source metadata')}</td>
        </tr>`).join('') : `
        <tr>
          <td colspan="5" style="text-align: center; color: var(--accent); padding: 24px;">✓ Zero citation defects detected. Manuscript ready for submission.</td>
        </tr>`}
      </tbody>
    </table>

    <div class="footer">
      Generated by <b>CiteAssist AI</b> — Pre-Submission Submission Firewall for Researchers.
    </div>
  </div>
</body>
</html>`;

  // 3. JSON Output
  const json = JSON.stringify({ metadata: meta, findings }, null, 2);

  // 4. PI Handoff Email template (plain text, no DOM required)
  const piEmailBody = [
    `Subject: CiteAssist Pre-Flight Report — Action Required Before Submission`,
    ``,
    `Hi PI / Co-Author,`,
    ``,
    `The automated Pre-Flight Dossier for "${meta.manuscriptTitle}" has flagged the`,
    `following issues that may trigger a desk rejection at your target venue:`,
    ``,
    `  🔴  Retracted Citations:       ${meta.retractionCount}`,
    `  🟡  Broken / Dead DOIs:        ${meta.brokenDoiCount}`,
    `  🔵  Missing Canonical Baselines: ${baselineCount}`,
    `  ⚪  Missing BibTeX Entries:    ${meta.missingBibCount}`,
    ``,
    `Desk-Rejection Risk Score: ${meta.deskRejectionScore}/100 — ${riskStatus}`,
    ``,
    `Please review the attached HTML dossier and resolve the highlighted items`,
    `before the submission deadline.`,
    ``,
    `Audit timestamp: ${dateFormatted}`,
    ``,
    `Generated by CiteAssist AI — https://citeassist.ai`,
    `(Pre-Submission Citation Firewall for Researchers)`,
  ].join('\n');

  // 5. Download Helper
  const downloadAs = (format: 'html' | 'md' | 'json', customName?: string) => {
    if (typeof window === 'undefined') return;
    const baseName = customName || meta.manuscriptTitle.replace(/\.[^/.]+$/, '') || 'preflight-dossier';
    let blob: Blob;
    const ext = format;

    if (format === 'html') {
      blob = new Blob([html], { type: 'text/html;charset=utf-8' });
    } else if (format === 'md') {
      blob = new Blob([markdown], { type: 'text/markdown;charset=utf-8' });
    } else {
      blob = new Blob([json], { type: 'application/json;charset=utf-8' });
    }

    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${baseName}_dossier.${ext}`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  // 6. PI Handoff Email accessor (pure string — no DOM required)
  const copyPIHandoffEmail = () => piEmailBody;

  return { markdown, html, json, downloadAs, copyPIHandoffEmail };
}
