'use client';

import React, { useState } from 'react';
import { useReciteStore } from '@/lib/store';
import { cn } from '@/lib/utils';
import { Download, FileText, X, AlertTriangle, Database, CheckCircle2 } from 'lucide-react';

interface ExportModalProps {
  isOpen: boolean;
  onClose: () => void;
}

export default function ExportModal({ isOpen, onClose }: ExportModalProps) {
  const { claims, documentTitle } = useReciteStore();
  const [isExporting, setIsExporting] = useState(false);

  if (!isOpen) return null;

  // Calculate resolution metrics
  const totalClaims = claims.length;
  const acceptedClaims = claims.filter((c) => c.status === 'accepted' && c.acceptedPaper);
  const unverifiedCount = totalClaims - acceptedClaims.length;

  // Generate BibTeX string locally
  const handleExportBib = async () => {
    setIsExporting(true);

    try {
      await new Promise((resolve) => setTimeout(resolve, 600));

      let bibtexContent = `% Generated by ReciteAI Pre-Flight Console\n% Document: ${documentTitle}\n\n`;

      acceptedClaims.forEach((claim, idx) => {
        const paper = claim.acceptedPaper!;
        const firstAuthor =
          paper.authors?.[0]?.split(' ').pop()?.replace(/[^a-zA-Z]/g, '') || 'Unknown';
        const bibKey = `${firstAuthor}${paper.year || 'ND'}_${idx}`;

        bibtexContent += `@article{${bibKey},\n`;
        bibtexContent += `  title = {${paper.title}},\n`;
        if (paper.authors && paper.authors.length > 0) {
          bibtexContent += `  author = {${paper.authors.join(' and ')}},\n`;
        }
        if (paper.year) bibtexContent += `  year = {${paper.year}},\n`;
        if (paper.doi) bibtexContent += `  doi = {${paper.doi.replace('https://doi.org/', '')}},\n`;
        if (paper.url) bibtexContent += `  url = {${paper.url}}\n`;
        bibtexContent += `}\n\n`;
      });

      const blob = new Blob([bibtexContent], { type: 'text/plain;charset=utf-8' });
      const url = URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = `reciteai_export_${documentTitle.replace('.tex', '')}.bib`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(url);

      onClose();
    } catch (error) {
      console.error('Export failed:', error);
    } finally {
      setIsExporting(false);
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-zinc-950/60 backdrop-blur-sm animate-in fade-in duration-100 font-sans">
      {/* Modal Container */}
      <div className="relative w-full max-w-md bg-white dark:bg-zinc-950 border border-zinc-200 dark:border-zinc-800 rounded-xl shadow-2xl overflow-hidden flex flex-col font-sans select-none animate-in zoom-in-95 duration-100 text-zinc-900 dark:text-zinc-100">
        {/* Header */}
        <div className="h-11 border-b border-zinc-200 dark:border-zinc-800 bg-zinc-50 dark:bg-zinc-900/60 flex items-center justify-between px-4">
          <div className="flex items-center space-x-2">
            <Download className="w-4 h-4 text-emerald-600 dark:text-emerald-400" />
            <span className="text-xs font-mono font-bold tracking-wider text-zinc-800 dark:text-zinc-200">
              EXPORT BIBLIOGRAPHY
            </span>
          </div>
          <button
            onClick={onClose}
            className="text-zinc-400 hover:text-zinc-700 dark:hover:text-zinc-200 transition-colors p-1 rounded hover:bg-zinc-200 dark:hover:bg-zinc-800"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* Body */}
        <div className="p-5 space-y-5">
          {/* Status HUD */}
          <div className="grid grid-cols-2 gap-3 font-sans">
            <div className="bg-zinc-50 dark:bg-zinc-900/60 border border-zinc-200 dark:border-zinc-800 p-3 rounded-lg flex flex-col items-center justify-center text-center">
              <CheckCircle2 className="w-5 h-5 text-emerald-500 mb-1" />
              <span className="text-xl font-mono text-emerald-600 dark:text-emerald-400 font-bold leading-none mb-1">
                {acceptedClaims.length}
              </span>
              <span className="text-[10px] font-mono text-zinc-500 uppercase tracking-wider">
                VERIFIED CITATIONS
              </span>
            </div>

            <div
              className={cn(
                'border p-3 rounded-lg flex flex-col items-center justify-center text-center transition-colors',
                unverifiedCount > 0
                  ? 'bg-yellow-50/50 dark:bg-yellow-950/20 border-yellow-300 dark:border-yellow-900/50'
                  : 'bg-zinc-50 dark:bg-zinc-900/60 border-zinc-200 dark:border-zinc-800'
              )}
            >
              {unverifiedCount > 0 ? (
                <AlertTriangle className="w-5 h-5 text-yellow-500 mb-1" />
              ) : (
                <CheckCircle2 className="w-5 h-5 text-emerald-500 mb-1 opacity-50" />
              )}
              <span
                className={cn(
                  'text-xl font-mono font-bold leading-none mb-1',
                  unverifiedCount > 0 ? 'text-yellow-700 dark:text-yellow-400' : 'text-zinc-500'
                )}
              >
                {unverifiedCount}
              </span>
              <span className="text-[10px] font-mono text-zinc-500 uppercase tracking-wider">
                UNVERIFIED CLAIMS
              </span>
            </div>
          </div>

          {unverifiedCount > 0 && (
            <div className="flex items-start space-x-2 p-2.5 bg-yellow-500/10 border border-yellow-500/30 rounded-lg text-yellow-900 dark:text-yellow-200">
              <AlertTriangle className="w-4 h-4 text-yellow-500 shrink-0 mt-0.5" />
              <p className="text-[11px] leading-relaxed">
                Notice: {unverifiedCount} claims remain unverified. These will be excluded from the generated .bib file.
              </p>
            </div>
          )}

          {/* Action Buttons */}
          <div className="space-y-2.5 pt-1">
            <button
              onClick={handleExportBib}
              disabled={isExporting || acceptedClaims.length === 0}
              className="w-full flex items-center justify-between px-3.5 py-2.5 bg-emerald-500/10 hover:bg-emerald-500/20 text-emerald-700 dark:text-emerald-300 border border-emerald-500/30 rounded-lg transition-all disabled:opacity-50 disabled:cursor-not-allowed group shadow-xs"
            >
              <div className="flex items-center space-x-2.5">
                <Database className="w-4 h-4" />
                <div className="flex flex-col text-left">
                  <span className="text-xs font-bold font-sans">Export .bib Database</span>
                  <span className="text-[10px] text-emerald-600 dark:text-emerald-400/80">Standard BibTeX bibliography format</span>
                </div>
              </div>
              <Download className="w-4 h-4 group-hover:translate-y-0.5 transition-transform" />
            </button>

            <button
              disabled={true}
              className="w-full flex items-center justify-between px-3.5 py-2.5 bg-zinc-100 dark:bg-zinc-900/60 text-zinc-400 dark:text-zinc-600 border border-zinc-200 dark:border-zinc-800 rounded-lg cursor-not-allowed text-left"
            >
              <div className="flex items-center space-x-2.5">
                <FileText className="w-4 h-4" />
                <div className="flex flex-col text-left">
                  <span className="text-xs font-semibold">Download Annotated .tex</span>
                  <span className="text-[10px]">Auto-injects \cite&#123;&#125; markers into draft</span>
                </div>
              </div>
              <span className="text-[9px] font-mono border border-zinc-200 dark:border-zinc-700 px-1.5 py-0.2 rounded bg-zinc-200/60 dark:bg-zinc-800 text-zinc-500">
                Phase 2
              </span>
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}