'use client';

import React, { useState } from 'react';
import { useReciteStore } from '@/lib/store';
import { cn } from '@/lib/utils';
import { Download, FileText, X, AlertTriangle, Database, CheckCircle2, Globe, FileCode2, Copy, Check } from 'lucide-react';
import { ReportGenerator } from '@/services/report-generator';

interface ExportModalProps {
  isOpen: boolean;
  onClose: () => void;
}

export default function ExportModal({ isOpen, onClose }: ExportModalProps) {
  const { claims, documentTitle, docMetrics } = useReciteStore();
  const [isExporting, setIsExporting] = useState(false);
  const [copiedOverleaf, setCopiedOverleaf] = useState(false);

  if (!isOpen) return null;

  const totalClaims = claims.length;
  const acceptedClaims = claims.filter((c) => c.status === 'accepted');
  const unverifiedCount = totalClaims - acceptedClaims.length;

  const downloadFile = (filename: string, content: string, mimeType: string) => {
    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  // Export Patched LaTeX Manuscript
  const handleExportPatchedTex = () => {
    const { rawText, parsedText, addToast } = useReciteStore.getState();
    const tex = rawText || parsedText || '';
    if (!tex) {
      addToast('No manuscript loaded to export.', 'warning');
      return;
    }
    const cleanName = documentTitle.endsWith('.tex') ? `clean_${documentTitle}` : `${documentTitle}_clean.tex`;
    downloadFile(cleanName, tex, 'text/x-tex;charset=utf-8');
    addToast('Downloaded patched LaTeX manuscript.', 'success');
    onClose();
  };

  // Copy Patched LaTeX for Overleaf
  const handleCopyOverleaf = () => {
    const { rawText, parsedText, addToast } = useReciteStore.getState();
    const tex = rawText || parsedText || '';
    if (!tex) {
      addToast('No manuscript loaded to copy.', 'warning');
      return;
    }
    navigator.clipboard.writeText(tex).then(() => {
      setCopiedOverleaf(true);
      addToast('Patched LaTeX copied! Paste directly into your Overleaf main.tex.', 'success');
      setTimeout(() => setCopiedOverleaf(false), 2000);
    }).catch(() => {
      addToast('Failed to copy to clipboard.', 'error');
    });
  };

  // Export Standard BibTeX
  const handleExportBib = async () => {
    setIsExporting(true);
    try {
      let bibtexContent = `% Generated by ReciteAI Pre-Flight Console\n% Document: ${documentTitle}\n\n`;
      acceptedClaims.forEach((claim, idx) => {
        const paper = claim.acceptedPaper;
        if (!paper) return;
        const firstAuthor =
          paper.authors?.[0]?.split(' ').pop()?.replace(/[^a-zA-Z]/g, '') || 'Unknown';
        const bibKey = `${firstAuthor}${paper.year || 'ND'}_${idx}`;

        bibtexContent += `@article{${bibKey},\n`;
        bibtexContent += `  title = {${paper.title}},\n`;
        if (paper.authors && paper.authors.length > 0) {
          bibtexContent += `  author = {${paper.authors.join(' and ')}},\n`;
        }
        if (paper.year) bibtexContent += `  year = {${paper.year}},\n`;
        if (paper.doi) bibtexContent += `  doi = {${paper.doi.replace('https://doi.org/', '')}},\n`;
        if (paper.url) bibtexContent += `  url = {${paper.url}}\n`;
        bibtexContent += `}\n\n`;
      });

      downloadFile(`reciteai_export_${documentTitle.replace('.tex', '')}.bib`, bibtexContent, 'text/plain;charset=utf-8');
      onClose();
    } finally {
      setIsExporting(false);
    }
  };

  // Export Markdown Report
  const handleExportMarkdown = () => {
    const md = ReportGenerator.generateMarkdownReport(documentTitle, claims, docMetrics);
    downloadFile(`audit_report_${documentTitle.replace('.tex', '')}.md`, md, 'text/markdown;charset=utf-8');
    onClose();
  };

  // Export HTML Report
  const handleExportHtml = () => {
    const html = ReportGenerator.generateHtmlReport(documentTitle, claims, docMetrics);
    downloadFile(`audit_report_${documentTitle.replace('.tex', '')}.html`, html, 'text/html;charset=utf-8');
    onClose();
  };

  // Export LaTeX Appendix
  const handleExportLatex = () => {
    const tex = ReportGenerator.generateLatexAppendix(documentTitle, claims);
    downloadFile(`audit_appendix_${documentTitle.replace('.tex', '')}.tex`, tex, 'text/x-tex;charset=utf-8');
    onClose();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-zinc-950/60 backdrop-blur-sm animate-in fade-in duration-100 font-sans">
      <div className="relative w-full max-w-lg bg-[#0E1115] border border-[#21262D] rounded-xl shadow-2xl overflow-hidden flex flex-col font-sans select-none animate-in zoom-in-95 duration-100 text-neutral-100">
        {/* Header */}
        <div className="h-11 border-b border-[#21262D] bg-[#14181D] flex items-center justify-between px-4">
          <div className="flex items-center space-x-2">
            <Download className="w-4 h-4 text-emerald-400" />
            <span className="text-xs font-mono font-bold tracking-wider text-neutral-200 uppercase">
              Export Peer-Review Audit Artifacts
            </span>
          </div>
          <button
            onClick={onClose}
            className="text-neutral-400 hover:text-white transition-colors p-1 rounded hover:bg-[#21262D]"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* Body */}
        <div className="p-5 space-y-4">
          {/* Status KPI Cards */}
          <div className="grid grid-cols-2 gap-3">
            <div className="bg-[#14181D] border border-[#21262D] p-3 rounded-lg flex flex-col items-center justify-center text-center">
              <CheckCircle2 className="w-5 h-5 text-emerald-400 mb-1" />
              <span className="text-xl font-mono text-emerald-400 font-bold leading-none mb-1">
                {acceptedClaims.length}
              </span>
              <span className="text-[10px] font-mono text-neutral-400 uppercase tracking-wider">
                VERIFIED CITATIONS
              </span>
            </div>

            <div
              className={cn(
                'border p-3 rounded-lg flex flex-col items-center justify-center text-center transition-colors',
                unverifiedCount > 0
                  ? 'bg-amber-950/20 border-amber-500/30'
                  : 'bg-[#14181D] border-[#21262D]'
              )}
            >
              {unverifiedCount > 0 ? (
                <AlertTriangle className="w-5 h-5 text-amber-400 mb-1" />
              ) : (
                <CheckCircle2 className="w-5 h-5 text-emerald-400 mb-1 opacity-50" />
              )}
              <span
                className={cn(
                  'text-xl font-mono font-bold leading-none mb-1',
                  unverifiedCount > 0 ? 'text-amber-300' : 'text-neutral-400'
                )}
              >
                {unverifiedCount}
              </span>
              <span className="text-[10px] font-mono text-neutral-400 uppercase tracking-wider">
                UNVERIFIED CLAIMS
              </span>
            </div>
          </div>

          {/* Export Options Grid */}
          <div className="space-y-2 pt-1 text-xs">
            {/* 0A. Copy Patched LaTeX for Overleaf */}
            <button
              onClick={handleCopyOverleaf}
              className="w-full flex items-center justify-between px-3.5 py-2.5 bg-emerald-950/40 hover:bg-emerald-950/70 text-neutral-200 border border-emerald-500/60 hover:border-emerald-400 rounded-lg transition-all cursor-pointer group shadow-[0_0_12px_rgba(16,185,129,0.25)]"
            >
              <div className="flex items-center space-x-3">
                <Copy className="w-4 h-4 text-emerald-400" />
                <div className="flex flex-col text-left">
                  <span className="font-semibold text-emerald-200">Copy Patched LaTeX for Overleaf</span>
                  <span className="text-[10px] text-neutral-400">Copies full updated .tex text directly to clipboard</span>
                </div>
              </div>
              {copiedOverleaf ? (
                <Check className="w-4 h-4 text-emerald-400" />
              ) : (
                <span className="text-[10px] font-mono text-emerald-400 uppercase font-bold">1-Click</span>
              )}
            </button>

            {/* 0B. Download Patched LaTeX */}
            <button
              onClick={handleExportPatchedTex}
              className="w-full flex items-center justify-between px-3.5 py-2.5 bg-[#14181D] hover:bg-[#1A2026] text-neutral-200 border border-[#262C34] hover:border-emerald-500/50 rounded-lg transition-all cursor-pointer group"
            >
              <div className="flex items-center space-x-3">
                <FileCode2 className="w-4 h-4 text-emerald-400" />
                <div className="flex flex-col text-left">
                  <span className="font-semibold text-neutral-100">Download Clean LaTeX (.tex)</span>
                  <span className="text-[10px] text-neutral-400">Patched manuscript file with all verified citations injected</span>
                </div>
              </div>
              <Download className="w-4 h-4 text-neutral-400 group-hover:text-emerald-400 transition-colors" />
            </button>

            {/* 1. BibTeX */}
            <button
              onClick={handleExportBib}
              disabled={isExporting || acceptedClaims.length === 0}
              className="w-full flex items-center justify-between px-3.5 py-2.5 bg-[#14181D] hover:bg-[#1A2026] text-neutral-200 border border-[#262C34] hover:border-emerald-500/50 rounded-lg transition-all cursor-pointer group"
            >
              <div className="flex items-center space-x-3">
                <Database className="w-4 h-4 text-emerald-400" />
                <div className="flex flex-col text-left">
                  <span className="font-semibold text-neutral-100">BibTeX Database (.bib)</span>
                  <span className="text-[10px] text-neutral-400">Standard bibliography format for LaTeX / Overleaf</span>
                </div>
              </div>
              <Download className="w-4 h-4 text-neutral-400 group-hover:text-emerald-400 transition-colors" />
            </button>

            {/* 2. Markdown Report */}
            <button
              onClick={handleExportMarkdown}
              className="w-full flex items-center justify-between px-3.5 py-2.5 bg-[#14181D] hover:bg-[#1A2026] text-neutral-200 border border-[#262C34] hover:border-sky-500/50 rounded-lg transition-all cursor-pointer group"
            >
              <div className="flex items-center space-x-3">
                <FileText className="w-4 h-4 text-sky-400" />
                <div className="flex flex-col text-left">
                  <span className="font-semibold text-neutral-100">Markdown Peer-Review Report (.md)</span>
                  <span className="text-[10px] text-neutral-400">Telemetry breakdown, NLI metrics, and DOI index</span>
                </div>
              </div>
              <Download className="w-4 h-4 text-neutral-400 group-hover:text-sky-400 transition-colors" />
            </button>

            {/* 3. Interactive HTML Summary */}
            <button
              onClick={handleExportHtml}
              className="w-full flex items-center justify-between px-3.5 py-2.5 bg-[#14181D] hover:bg-[#1A2026] text-neutral-200 border border-[#262C34] hover:border-teal-500/50 rounded-lg transition-all cursor-pointer group"
            >
              <div className="flex items-center space-x-3">
                <Globe className="w-4 h-4 text-teal-400" />
                <div className="flex flex-col text-left">
                  <span className="font-semibold text-neutral-100">Interactive HTML Summary (.html)</span>
                  <span className="text-[10px] text-neutral-400">Self-contained browser report with dark theme</span>
                </div>
              </div>
              <Download className="w-4 h-4 text-neutral-400 group-hover:text-teal-400 transition-colors" />
            </button>

            {/* 4. LaTeX Appendix */}
            <button
              onClick={handleExportLatex}
              className="w-full flex items-center justify-between px-3.5 py-2.5 bg-[#14181D] hover:bg-[#1A2026] text-neutral-200 border border-[#262C34] hover:border-amber-500/50 rounded-lg transition-all cursor-pointer group"
            >
              <div className="flex items-center space-x-3">
                <FileCode2 className="w-4 h-4 text-amber-400" />
                <div className="flex flex-col text-left">
                  <span className="font-semibold text-neutral-100">LaTeX Appendix Section (.tex)</span>
                  <span className="text-[10px] text-neutral-400">Ready for \input&#123;audit_appendix&#125; in final submission</span>
                </div>
              </div>
              <Download className="w-4 h-4 text-neutral-400 group-hover:text-amber-400 transition-colors" />
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}