'use client';

import React, { useState } from 'react';
import { useCiteGuardStore } from '@/lib/store';
import { cn } from '@/lib/utils';
import { Download, FileText, X, AlertTriangle, Database, CheckCircle2 } from 'lucide-react';

interface ExportModalProps {
  isOpen: boolean;
  onClose: () => void;
}

export default function ExportModal({ isOpen, onClose }: ExportModalProps) {
  const { claims, documentTitle } = useCiteGuardStore();
  const [isExporting, setIsExporting] = useState(false);

  if (!isOpen) return null;

  // Calculate resolution metrics
  const totalClaims = claims.length;
  const acceptedClaims = claims.filter(c => c.status === 'accepted' && c.acceptedPaper);
  const unverifiedCount = totalClaims - acceptedClaims.length;

  // Generate BibTeX string locally
  const handleExportBib = async () => {
    setIsExporting(true);
    
    try {
      // Simulate small compiling delay for UX
      await new Promise(resolve => setTimeout(resolve, 800));

      let bibtexContent = `% Generated by ReciteAI Telemetry Console\n% Document: ${documentTitle}\n\n`;

      acceptedClaims.forEach((claim, idx) => {
        const paper = claim.acceptedPaper!;
        // Create a safe BibTeX key (e.g., Smith2023)
        const firstAuthor = paper.authors?.[0]?.split(' ').pop()?.replace(/[^a-zA-Z]/g, '') || 'Unknown';
        const bibKey = `${firstAuthor}${paper.year || 'ND'}_${idx}`;

        bibtexContent += `@article{${bibKey},\n`;
        bibtexContent += `  title = {${paper.title}},\n`;
        if (paper.authors && paper.authors.length > 0) {
          bibtexContent += `  author = {${paper.authors.join(' and ')}},\n`;
        }
        if (paper.year) bibtexContent += `  year = {${paper.year}},\n`;
        if (paper.doi) bibtexContent += `  doi = {${paper.doi.replace('https://doi.org/', '')}},\n`;
        if (paper.url) bibtexContent += `  url = {${paper.url}}\n`;
        bibtexContent += `}\n\n`;
      });

      // Create a downloadable blob
      const blob = new Blob([bibtexContent], { type: 'text/plain;charset=utf-8' });
      const url = URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = `reciteai_export_${documentTitle.replace('.tex', '')}.bib`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(url);

      onClose();
    } catch (error) {
      console.error('Export failed:', error);
    } finally {
      setIsExporting(false);
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-zinc-950/80 backdrop-blur-sm">
      {/* Modal Container */}
      <div className="relative w-full max-w-md bg-zinc-950 border border-zinc-800 shadow-2xl rounded-lg overflow-hidden flex flex-col font-sans animate-in fade-in zoom-in-95 duration-200">
        
        {/* Header */}
        <div className="h-12 border-b border-zinc-800 bg-zinc-900/50 flex items-center justify-between px-4">
          <div className="flex items-center space-x-2 text-zinc-300">
            <Download className="w-4 h-4 text-emerald-400" />
            <span className="text-xs font-mono tracking-widest font-bold">EXPORT CONSOLE</span>
          </div>
          <button 
            onClick={onClose}
            className="text-zinc-500 hover:text-zinc-300 transition-colors"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* Body */}
        <div className="p-6 space-y-6">
          
          {/* Status HUD */}
          <div className="grid grid-cols-2 gap-4">
            <div className="bg-zinc-900/50 border border-zinc-800 p-3 rounded flex flex-col items-center justify-center text-center">
              <CheckCircle2 className="w-6 h-6 text-emerald-500 mb-2" />
              <span className="text-2xl font-mono text-emerald-400 leading-none mb-1">{acceptedClaims.length}</span>
              <span className="text-[9px] font-mono text-zinc-500 tracking-wider">RESOLVED CITATIONS</span>
            </div>
            
            <div className={cn(
              "border p-3 rounded flex flex-col items-center justify-center text-center transition-colors",
              unverifiedCount > 0 
                ? "bg-amber-950/20 border-amber-900/50" 
                : "bg-zinc-900/50 border-zinc-800"
            )}>
              {unverifiedCount > 0 ? (
                <AlertTriangle className="w-6 h-6 text-amber-500 mb-2" />
              ) : (
                <CheckCircle2 className="w-6 h-6 text-emerald-500 mb-2 opacity-50" />
              )}
              <span className={cn(
                "text-2xl font-mono leading-none mb-1",
                unverifiedCount > 0 ? "text-amber-400" : "text-zinc-500"
              )}>
                {unverifiedCount}
              </span>
              <span className="text-[9px] font-mono text-zinc-500 tracking-wider">UNVERIFIED CLAIMS</span>
            </div>
          </div>

          {unverifiedCount > 0 && (
            <div className="flex items-start space-x-2 p-3 bg-amber-500/10 border border-amber-500/30 rounded text-amber-200/80">
              <AlertTriangle className="w-4 h-4 text-amber-400 shrink-0 mt-0.5" />
              <p className="text-[10px] font-mono leading-relaxed">
                Warning: You are exporting with {unverifiedCount} claims still unresolved. These will be ignored in the final .bib output.
              </p>
            </div>
          )}

          {/* Action Buttons */}
          <div className="space-y-3 pt-2">
            <button 
              onClick={handleExportBib}
              disabled={isExporting || acceptedClaims.length === 0}
              className="w-full flex items-center justify-between px-4 py-3 bg-emerald-500/10 hover:bg-emerald-500/20 text-emerald-400 border border-emerald-500/30 rounded transition-all disabled:opacity-50 disabled:cursor-not-allowed group"
            >
              <div className="flex items-center space-x-3">
                <Database className="w-4 h-4" />
                <div className="flex flex-col text-left">
                  <span className="text-xs font-bold font-mono">EXPORT .BIB DATABASE</span>
                  <span className="text-[9px] text-emerald-500/80 font-mono">Standard BibTeX format for LaTeX/Overleaf</span>
                </div>
              </div>
              <Download className="w-4 h-4 group-hover:translate-y-0.5 transition-transform" />
            </button>

            <button 
              disabled={true} // Disabled for now until reverse-splicing is built
              className="w-full flex items-center justify-between px-4 py-3 bg-zinc-900 text-zinc-500 border border-zinc-800 rounded cursor-not-allowed"
              title="Coming in Phase 2"
            >
              <div className="flex items-center space-x-3">
                <FileText className="w-4 h-4" />
                <div className="flex flex-col text-left">
                  <span className="text-xs font-bold font-mono">DOWNLOAD INJECTED .TEX</span>
                  <span className="text-[9px] font-mono">Auto-splices \cite{} markers into manuscript</span>
                </div>
              </div>
              <span className="text-[8px] font-mono border border-zinc-700 px-1.5 py-0.5 rounded bg-zinc-800">LOCKED</span>
            </button>
          </div>

        </div>
      </div>
    </div>
  );
}